# Generated by Django 3.0.8 on 2020-09-09 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='writer.Argument'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='procon',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='root',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='writer.Thought'),
            preserve_default=False,
        ),
    ]
