# Generated by Django 3.0.8 on 2020-09-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_auto_20200909_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='strength',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='sources',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
