# Generated by Django 3.0.8 on 2020-10-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_auto_20200909_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='smallId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='thought',
            name='smallId',
            field=models.IntegerField(default=-1),
        ),
    ]
