# Generated by Django 3.0.8 on 2020-11-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_auto_20201023_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
